### ISSUE TITLE
graph_plot question

### ISSUE THREAD

**Issue by cartal** [sistm/cytometree#1]
Hi, 

I have been playing aorunf with cytometree and my results look quite exciting! However, I have a problem with displaying the tree. 

Could you please provide more explanation/documentation on how to change the node size and maybe on how to expand the tree horizontally? 

Thanks

**Comment by chariff** [comment]
Hello,

Glad you are using cytometree. Change the node size by adjusting the `vertex.size` parameter. Please note that it will not automatically rescale the text in the node. You can adjust the text size by using the `Vcex` parameter. 

As for the how to expand the tree horizontally, unfortunatly the size of the tree is bounded by the size of the plot window. Ajust the size of the window (and ajust the `Vcex` and `vertex.size` accordingly.

Chariff
