### ISSUE TITLE
Expandability to multimodal expression distribution?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [sistm/cytometree#11]
Hi there, 

Thank you for the package. I was wondering if you might have any handy way to apply `cytometree` to marker expression distributions that are more than 2 modes?

Also, is it possible to use the package directly to the flow data processed as a SingleCellExperiments (`sce`) class?

Thank you!

**Comment by borishejblum** [comment]
Hi,

Thank you for your interest in `cytometree`.

While `cytometree` rely on binary trees, in practice it can split a marker several times over, making it suitable for distributions with more than 2 modes. In particular, in the post-processing of the results with `Annotation`, the `K3markers` markers argument can be used to specified which markers should be splitted into 3 expression levels.

Unfortunately, `cytometree` is not currently streamlined to use the `SingleCellExperiments` class directly. However, it is fairly straightforward to retrieve the necessary elements from on `sce` object and input them into `cytometree`. If you want to offer a pull request adding this functionnality, I will be happy to review it and add it into the package.

Best,
Boris
