### ISSUE TITLE
Misc issues

### ISSUE THREAD

**Issue by SamGG** [sistm/cytometree#2]
Hi,
I started using this package on simulated hypercube data and I get separated clusters nicely and easily. Very good job!

Some suggestions:
* it would be easier for reading the code and maintaining it to set name to the slots of the results, especially the slots of pl_list. For example, pl_list[[2]] should be named nodes and then could be easily accessed as pl_list$nodes
* in the plot_nodes function, I don't get why the maxxsup is computed over y https://github.com/sistm/cytometree/blob/60243bd0cb072a9c7c49d28c7a09328b7488c9ec/R/plot_nodes.R#L37
* maybe others later ;-)

Best.

**Comment by borishejblum** [comment]
Hi Sam,

Thanks for your interest in our software ! 

Thanks for your input on our code, we will look into this as soon as we have time. Meanwhile, we welcome pull requests (that would certainly speed things up in addressing your comments).

Best,
Boris

**Comment by SamGG** [comment]
But I have to find time me too ;-)
Thanks for your quick reply.

**Comment by borishejblum** [comment]
Those 2 points have been sorted in commits [70a69eb](https://github.com/sistm/cytometree/commit/70a69eb3253d80479fde7b5eb2facca8e7bcb3c7) and [aa94cd](https://github.com/sistm/cytometree/commit/6aa94cd7c6cf16762756c275caa83a853fb298b6).
