### ISSUE TITLE
Plot nodes in one or more pages

### ISSUE THREAD

**Issue by SamGG** [sistm/cytometree#3]
It would be nice to plot all nodes at once in an overview graphics that could span over multiple graphics or pages.
I think about something like 
```
row.per.page = 4 # this is an input aka a new option of the current function
col.per.page = 2 # this is an input aka a new option of the current function
nodes = unlist(pl_list[[2]])
pages = ceiling( length(nodes) / (col.per.page * row.per.page) )
par(mrfow = c(row.per.page, col.per.page)
loop across nodes...
```
Maybe you will consider changing the mar option of the par function in order to reduce space between graphics and moving the information of the subtitle as a second line in the main title.

**Comment by borishejblum** [comment]
Dear Sam, we have reworked the `plot_node()` function, and have incorporated your requested functionnalities (relying on the `cowplot` package) in commit [6aa94cd](https://github.com/sistm/cytometree/commit/6aa94cd7c6cf16762756c275caa83a853fb298b6).
