### ISSUE TITLE
Plot the count of populations

### ISSUE THREAD

**Issue by SamGG** [sistm/cytometree#4]
In order to get a quick and valuable information about the size of each population, I would be glad to have a graphics with population as x, count as y, y in log10 scale, using ggplot2. It would allow filtering out the smallest populations that have no meaning in some dataset.

**Comment by anthonydevaux** [comment]
Hi Sam,

Cytometree now features a `plot_cytopop ` function that plots the size of each cell population. 

Let us know if you come across any issue with it.

Thanks,

Anthony

**Comment by SamGG** [comment]
Hi! Thanks but I will have to delay the test. I will let you know. Best.
