### ISSUE TITLE
loading new fcs files

### ISSUE THREAD

**Issue by algebio** [sistm/cytometree#6]
Hi

I would like to try cytometree with my own data. What's the best way to load the data? I have tried with read.FCS and read.flowSet but it didn't work.

Regards
Juan

**Comment by borishejblum** [comment]
Hi Juan,

First thank you for your interest our work.

Could you be more specific: what did not work with `read.FCS()` ?
Currently, the main function in the `cytometree` package is `CytomeTree()`, which takes as input a matrix with the events (i.e. cells) as rows and the markers as columns. The output of `flowCore::read.FCS()` should contain such a matrix in its `@exprs` slot.

Best,
Boris

**Comment by algebio** [comment]
Hi Boris
It's working now. I was using @parameters instead.
Thank you so much for your help.
Juan
